default:
  tags: [build-cluster, sclable]

variables:
  IMAGE: eu.gcr.io/devops-155313/devops/build-bundle

stages: [lint, schedule, trigger]

lint:
  stage: lint
  image: ${IMAGE}:lts
  script:
  - hadolint Dockerfile
  - 

schedule:
  stage: schedule
  only: [schedules]
  image: ${IMAGE}:lts
  script:
  - ./fetch.sh
  - ./schedule.sh > gitlab-ci.yml
  artifacts:
    paths: [gitlab-ci.yml, '*.json']

trigger:
  stage: trigger
  only: [schedules]
  needs: [schedule]
  trigger:
    include:
    - artifact: gitlab-ci.yml
      job: schedule
    strategy: depend
