variables:
  IMAGE: eu.gcr.io/devops-155313/devops/build-bundle

stages: [schedule, trigger]

schedule:
  stage: schedule
  only: [schedules]
  image: ${IMAGE}:lts
  tags: [x-small]
  script:
  - ./schedule.sh > gitlab-ci.yml
  artifacts:
    when: always
    paths: [gitlab-ci.yml, '*.json']

trigger:
  stage: trigger
  only: [schedules]
  needs: [schedule]
  trigger:
    include:
    - artifact: gitlab-ci.yml
      job: schedule
    strategy: depend
