name: trigger

on:
  workflow_call:
    inputs:
      dockle:
        required: true
        type: string
      hadolint:
        required: true
        type: string
      java:
        required: true
        type: string
      node:
        required: true
        type: string
      ubuntu:
        required: true
        type: string
      self:
        required: true
        type: string
      tag:
        required: true
        type: string
          #secrets:
          #token:
          #required: true
          #type: string

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/lorenzleutgeb/build-bundle:${{ inputs.tag }}
        build-args: |
          DOCKLE_VERSION=${{ inputs.dockle }}
          HADOLINT_VERSION=${{ inputs.hadolint }}
          JAVA_VERSION=${{ java }}
          NODE_VERSION=${{ inputs.node }}
          UBUNTU_VERSION=${{ inputs.ubuntu }}
          SELF=${{ inputs.self }}
